### ISSUE TITLE
Compilation of zpaq fails

### ISSUE THREAD

**Issue by cyanate** [powturbo/TurboBench#7]
Dear Developer,
I've tried to compile with gcc 7.1.1 and got this error:
```
zpaq/libzpaq.o: In function `libzpaq::Array<int>::resize(unsigned long, int) [clone .constprop.129]':
libzpaq.cpp:(.text+0xf65): undefined reference to `libzpaq::error(char const*)'
libzpaq.cpp:(.text+0xfe0): undefined reference to `libzpaq::error(char const*)'
zpaq/libzpaq.o: In function `libzpaq::Array<unsigned short>::resize(unsigned long, int) [clone .constprop.131]':
libzpaq.cpp:(.text+0x1050): undefined reference to `libzpaq::error(char const*)'
libzpaq.cpp:(.text+0x10d0): undefined reference to `libzpaq::error(char const*)'
zpaq/libzpaq.o: In function `libzpaq::Array<unsigned char>::resize(unsigned long, int) [clone .constprop.132]':
libzpaq.cpp:(.text+0x1188): undefined reference to `libzpaq::error(char const*)'
zpaq/libzpaq.o:libzpaq.cpp:(.text+0x11a0): more undefined references to `libzpaq::error(char const*)' follow
collect2: error: ld returned 1 exit status
make: *** [makefile:436: turbobench] Error 1
```

**Comment by powturbo** [comment]
"libzpaq::error" is defined in "plugins.cc".
remove  the object file "plugins.o" and type make.
